# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from datetime import datetime
from typing_extensions import Literal, TypeAlias

from .job import Job
from .source import Source
from .upload import Upload
from .._models import BaseModel
from .api_file import APIFile

__all__ = [
    "UnwrapWebhookEvent",
    "Data",
    "DataNotificationPayloadJobCompleted",
    "DataNotificationPayloadJobFailed",
    "DataNotificationPayloadUploadCompleted",
    "DataNotificationPayloadUploadFailed",
]


class DataNotificationPayloadJobCompleted(BaseModel):
    files: Optional[List[APIFile]] = None
    """List of files generated by the job"""

    job: Optional[Job] = None


class DataNotificationPayloadJobFailed(BaseModel):
    job: Optional[Job] = None


class DataNotificationPayloadUploadCompleted(BaseModel):
    source: Optional[Source] = None

    upload: Optional[Upload] = None


class DataNotificationPayloadUploadFailed(BaseModel):
    upload: Optional[Upload] = None


Data: TypeAlias = Union[
    DataNotificationPayloadJobCompleted,
    DataNotificationPayloadJobFailed,
    DataNotificationPayloadUploadCompleted,
    DataNotificationPayloadUploadFailed,
]


class UnwrapWebhookEvent(BaseModel):
    id: Optional[str] = None
    """Unique identifier of the notification"""

    data: Optional[Data] = None
    """Event-specific payload data"""

    date: Optional[datetime] = None
    """Timestamp when the notification was sent"""

    event: Optional[
        Literal["job.completed", "job.failed", "job.cancelled", "upload.completed", "upload.failed", "upload.expired"]
    ] = None
    """Type of event that triggered the notification. Here are the possible events:

    - job.completed: A job has completed successfully
    - job.failed: A job has failed
    - job.cancelled: A job has been cancelled
    - upload.completed: An upload has completed successfully
    - upload.failed: An upload has failed
    - upload.expired: An upload has expired
    """
