# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional

from ..._models import BaseModel
from ..shared.response_ok import ResponseOk
from ..shared.chunkify_error import ChunkifyError

__all__ = ["TranscoderListResponse", "TranscoderListResponseData"]


class TranscoderListResponseData(BaseModel):
    id: Optional[str] = None
    """Unique identifier of the transcoder"""

    billable_time: Optional[int] = None
    """Billable time in seconds"""

    chunk_end_time: Optional[float] = None
    """End time of the current chunk in seconds"""

    chunk_number: Optional[int] = None
    """Number of the chunk being processed"""

    chunk_start_time: Optional[float] = None
    """Start time of the current chunk in seconds"""

    cpu_time: Optional[float] = None
    """CPU time used for transcoding in seconds"""

    created_at: Optional[str] = None
    """Timestamp when the status was created"""

    error: Optional[ChunkifyError] = None
    """Error message if the transcoding failed"""

    fps: Optional[float] = None
    """Current frames per second being processed"""

    frame: Optional[int] = None
    """Current frame number being processed"""

    job_id: Optional[str] = None
    """Unique identifier of the job"""

    out_time: Optional[int] = None
    """Current output time in seconds"""

    progress: Optional[float] = None
    """Progress percentage of the transcoding operation (0-100)"""

    speed: Optional[float] = None
    """Current processing speed multiplier"""

    status: Optional[str] = None
    """Current status of the transcoder (starting, transcoding, finished, error)"""

    transcoder_instance_id: Optional[str] = None
    """Unique identifier of the transcoder instance (generated by the transcoder)"""

    updated_at: Optional[str] = None
    """Timestamp when the status was last updated"""


class TranscoderListResponse(ResponseOk):
    data: List[TranscoderListResponseData]
